const { chromium } = require('playwright');
const path = require('path');
const fs = require('fs');
const root = path.resolve(__dirname, '..');
const shots = path.join(root, 'shots');
fs.mkdirSync(shots, { recursive: true });
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:1400,height:1000}});
await p.goto('file://' + path.join(root, 'index.html'));
await p.click('#themeSeg button[data-theme="dark"]');
await p.click('.navbtn[data-view="capability"]'); await p.waitForTimeout(300);
await p.screenshot({path:path.join(shots,'d-cap.png'),fullPage:true});
await p.click('.navbtn[data-view="dashboard"]'); await p.waitForTimeout(300);
await p.screenshot({path:path.join(shots,'d-dash.png'),fullPage:false});
await p.click('.navbtn[data-view="config"]'); await p.waitForTimeout(300);
await p.screenshot({path:path.join(shots,'d-config.png'),fullPage:true});
await b.close();})();
